### ISSUE TITLE
Option to Remove Sensors 

### ISSUE THREAD

**Issue by dvdcut** [pihome-shc/PiHomeHVAC#100]
no option to remove old sensors that i have for testing from gui, and they are showing in battery graphs with no value and i can see them under setting->node alerts.

**Comment by twa127** [comment]
Hi

Settings/Node and Zone Configuration/Sensors has a delete option for each sensor, does this not do what you want?

**Comment by dvdcut** [comment]
let me redeploy the system and i'll get back to you on this. i copied my nodes table from old system may be it is messing up with my MaxAir setup.

**Comment by pihome-shc** [comment]
@dvdcut i deployed new setup from github and i dont have any issues, i haven't compared table between version 1 and 2 best to re-deploy your system
