### ISSUE TITLE
Bug: Gateway setting

### ISSUE THREAD

**Issue by pihome-shc** [pihome-shc/PiHomeHVAC#117]
Further to comments by @dvdcut on Discord
dvdcut — 04/13/2021
on my new setup when i try to add gateway i looks confusing, i know this is once but best to hide fields based on gateway type selection.
after update Bug Fix - Gateway type default set to 'Serial' if gateway table empty #114 

**Gui shows no gateway,** 
![image](https://user-images.githubusercontent.com/33334232/114946346-eca1f800-9e42-11eb-921e-66e66e402239.png)

**gateway setting in database.**
![image](https://user-images.githubusercontent.com/33334232/114946394-fd526e00-9e42-11eb-9abf-9fbac74209c6.png)

**Comment by pihome-shc** [comment]
update: 
as soon as i select serial 
![image](https://user-images.githubusercontent.com/33334232/114946698-98e3de80-9e43-11eb-8669-d72ea7324ee9.png)

same goes for wifi but it is wrong ip address, 
![image](https://user-images.githubusercontent.com/33334232/114946733-aa2ceb00-9e43-11eb-896a-ba5a2bde15a6.png)

**Comment by twa127** [comment]
fix in commit #118
