### ISSUE TITLE
LoRa (RFM95) Nodes for better communication

### ISSUE THREAD

**Issue by dvdcut** [pihome-shc/PiHomeHVAC#141]
opening this issue to track LoRa (RFM95) Nodes including Hardware and Software. i m planning to move away from nRF.

**Comment by twa127** [comment]
I did my testing using the RF96

**Comment by pihome-shc** [comment]
I”ll publish this adapter pcb files later, it has support for rfm95/96 and rmf69. 
I tested pcb adapter connected to nrf socket with simple ping pong sketch with lora radio.

**Comment by twa127** [comment]
I tested with a serial gateway and a single 18650 battery powered temperature sensor, all good

**Comment by dvdcut** [comment]
did you test with gateway from pihome website or you made your own? i found adapter board you were talking about in old version [pihome website](https://www.pihome.eu/2020/02/16/nrf24l01-to-rfm69cw-rfm69hcw-rfm69w/) which points to [pihome github](https://github.com/pihome-shc/pihome/tree/master/PCB%20Related/PiHome%20RFM69-95%20to%20nRF) 
wondering is it straight swap of radio module and update the sketch ?

**Comment by twa127** [comment]
Tested with a home made veroboard gateway and mysensors temperature sensor, previously used with nrf, just updated the sketches and replaced the nrf modules with RF96 mounted on the adapter board.

**Comment by pihome-shc** [comment]
PCB files are already part MaxAir repo. have look [here ](https://github.com/pihome-shc/PiHomeHVAC/tree/main/PCB%20Related/PiHome%20RFM69-95%20to%20nRF)i know nRF have range issues specially if you have solid walls in between. nrf to rfm adaptor was designed to keep base hardware same and switch the radio.

**Comment by dvdcut** [comment]
thank you, i will give try to lora modules and open new case if required.
