### ISSUE TITLE
Latest Release - MaxAir version update 

### ISSUE THREAD

**Issue by dvdcut** [pihome-shc/PiHomeHVAC#152]
Under the System Configuration ->PiHome Update needs to change to MaxAir Update and also code in model needs to change, right now it checks the update location and update file location from system table and read version and compare it. 

i suggest we change this to get this information from github by changing update_location to https://github.com/pihome-shc/PiHomeHVAC and update_file to either to following two options: 

1. check latest release 
2. check [db_config.ini]( https://github.com/pihome-shc/PiHomeHVAC/blob/main/st_inc/db_config.ini)  for version and build number. 

```
//Pihome Update
echo '
<div class="modal fade" id="pihome_update" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
                <h5 class="modal-title">'.$lang['pihome_update'].'</h5>
            </div>
            <div class="modal-body">
			<p class="text-muted"> '.$lang['pihome_update_text'].' </p>';

		
echo '	<div class=\"list-group\">';
echo "                            <a href=\"#\" class=\"list-group-item\">
                                    <i class=\"fa fa-server fa-1x blueinfo\"></i> ".$lang['pihome_update_c_version']."
                                    <span class=\"pull-right text-muted small\"><em>".settings($conn, 'version')."</em>
                                    </span>
                                </a>"; 
ini_set('max_execution_time',90);
$getVersions = file_get_contents(''.settings($conn, 'update_location').''.settings($conn, 'update_file').'');
if ($getVersions != ''){
$versionList = explode("\n", $getVersions);	
	foreach ($versionList as $aV)
	{
		echo "<a href=\"settings.php?uid=10\"  class=\"list-group-item\">
        <i class=\"fa fa-download fa-1x blueinfo\"></i> ".$lang['pihome_update_u_version']."
        <span class=\"pull-right text-muted small\"><em>".$aV."</em></span>
         </a>";
	}
}	
echo '</div></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary btn-sm" data-dismiss="modal">'.$lang['close'].'</button>
            </div>
        </div>
    </div>
</div>'
```

**Comment by dvdcut** [comment]
To get latest release from github, we dont have first release for MaxAir so far so i used pihome url for this testing 

```
curl -s https://api.github.com/repos/pihome-shc/pihome/releases/latest | grep tag_name | cut -d '"' -f 4
curl -s https://api.github.com/repos/pihome-shc/PiHomeHVAC/releases/latest | grep tag_name | cut -d '"' -f 4
```

**Comment by pihome-shc** [comment]
i have added rules to firewall for current-release-versions.php and i'll let you know how many times pihome website serve this to users.

**Comment by twa127** [comment]
The version number is no longer adequate, as the update status is now dependent on code version, code build number and database version. Commit #156 uses a table to display the info held in both the local and github copies of file st_inc/db_config.ini

**Comment by twa127** [comment]
Hi,

#158 - added a function to schedule a check of installed code against GitHub repository and notify if any difference, with the option to install any updated code modules

**Comment by pihome-shc** [comment]
closing; so far update process proved to be working as expected
