### ISSUE TITLE
System Controller Settings

### ISSUE THREAD

**Issue by JSa1987** [pihome-shc/PiHomeHVAC#192]
Hello,

I have finally decided upgraded from PiHome to AirMax. :-)

I downloaded the AirMax standard image from pihome.eu, and then upgraded it to the latest revision from github.

After doing so I setup my system. I wanted to feedback that everything went quite well. I however had/have two little issues that I thought was worth reporting as this is a clean installation.

1. When I went to setup the System Controller Settings I found that the save button would not work. When clicking on save the menu will not close and the data entered was not written to the database. I had to manually updated the system_controller table with the heat_relay_id of my boiler and the other details.
2. The second issue (that might be related to the first one) is that on the home page when clicking on the Mode button the mode does not change. I had to manually update the system_controller.sc_mode to 1 to switch the system from OFF to TIMER.

**Comment by JSa1987** [comment]
I have made some progress with regards to the second issue. Found out that when I was clicking the button to change the mode I was getting following error:
```
Uncaught ReferenceError: active_sc_mode is not defined
    at <anonymous>:1:1
```
I therefore include `<script type="text/javascript" src="js/request.js"></script>` at the beginning of homelist.php (on line 27) and the button to change mode is now working. Not sure if this is the right spot where to add this.

With regards to the first issue I noticed I'm getting the following error:
```
Uncaught ReferenceError: system_controller_settings is not defined
    at HTMLInputElement.onclick (settings.php:1)
```
So I would suspect it is something similar, but not sure where to add the code.

**Comment by pihome-shc** [comment]
@JSa1987 can you download from dropbox and try this?
**https://www.dropbox.com/s/m32c8xfsny0sui2/RPI_MaxAir_1_00_060921.zip?dl=0**

**Comment by JSa1987** [comment]
@pihome-shc thank you! I will try to download this image, flash it to spare SD card, give it a try and feedback.
Just to confirm after using this image I should not upgrade to the latest revision from GitHub?

**Comment by twa127** [comment]
Always worth clearing the browser cache.
Try force an update check from Settings/System Configuration/ - MaxAir Update

**Comment by twa127** [comment]
The dropbox image contains everything except your last commit, just use Mair Update to get that

**Comment by JSa1987** [comment]
Hello,

I have started with a fresh image (RPI_MaxAir_1_00_060921.zip) , the forced an update check (from Settings/System Configuration/ - MaxAir Update) and then cleared the cache of my browser.
This fixed the second issue and I am now able to switch between moded.

With regards to the first issue when in System Controller Settings window now clicking on save does close the pop up (before it wouldn't do this). However, what is entered in this window (e.g. if I change the hysteresis time) does not get written to the database.
This is not a show stopper for me as I have adjusted the settings directly in the database, but something that might still need some investigation.

**Comment by twa127** [comment]
Hi, updating the hysteresis time works okay for me, the system_controller table is updated with the GUI value entered

**Comment by pihome-shc** [comment]
any further work required on this?

**Comment by pihome-shc** [comment]
can we close this issue if no further action required ?

**Comment by twa127** [comment]
I think @JSa1987 was happy after re-loading from the Dropbox image file, I vote close.
