### ISSUE TITLE
MySensor Relays

### ISSUE THREAD

**Issue by twa127** [pihome-shc/PiHomeHVAC#220]
Hi, we have recently gained some users who have MySensor Zone and Boiler relays and this has shown up a serious issue with MaxAir. This issue has existed since day 1, and has only now surfaced.

There were 2 problems:

- the first was that in the system controller section of controller.php the message_out queue was not constructed properly, the relay ID was used instead of the node ID and hence the gateway would never of been able to communicate with the relay. This was fixed in #216 
- the second problem arose because MaxAir activates relays based on either zone or boiler state change, this approach was taken to improve overall efficiency. Unfortunately MySensors relays require constantly to be refreshed and in the case of the boiler relay for the message to be sent twice. 

The first problem has been resolved, a fix for the second is ongoing.

**Comment by pihome-shc** [comment]
no only boiler controller is expecting message from MaxAir but also zone controller, this was implemented as safety function for Zone: If Zone Controller loses connection with gateway or system crashes zone will turn off at set time. and same goes for boiler controller.

**Comment by twa127** [comment]
fixed in #216
