### ISSUE TITLE
Scheduling Issue

### ISSUE THREAD

**Issue by twa127** [pihome-shc/PiHomeHVAC#221]
Hi,

seeing reports that commit #219 is causing problems, not yet been able to investigate

**Comment by twa127** [comment]
I see the problem that @JSa1987 is trying to fix but function get_schedule_status is only intended to check one schedule, the problem is real but the fix is more complex than #219

**Comment by twa127** [comment]
I think #219 should be backed out ASAP, it causes more problems than it tries to solve

**Comment by twa127** [comment]
The issue relates to instances where there is more than 1 schedule for a particular zone on a particular day. I will work on a fix for this issue, please bear with me.

**Comment by twa127** [comment]
fixed in #222

**Comment by pihome-shc** [comment]
can this issue be closed ?

**Comment by twa127** [comment]
Fixed
