### ISSUE TITLE
Unsafe database update #226

### ISSUE THREAD

**Issue by twa127** [pihome-shc/PiHomeHVAC#229]
database update 250921.sql makes a table change by dropping the table and hence any data it contained, rather than making a table alteration

**Comment by pihome-shc** [comment]
@twa127 i think we have to modify exiting database, i know this is no the right way to do as system already deployed have this applied but to avoid future deployments its best to modify but open to suggestions

**Comment by twa127** [comment]
Yes, just trying to make the point that this is not the way to change the database, updates are meant to be cumulative and not damage any existing data, this can hopefully always be achieved through the SQL contained in the update. Obviously dropping a table without already having moved the data could result in a user having to rebuild their configuration.

**Comment by JSa1987** [comment]
@twa127 this was done this way only because at the time nobody was using the features based on that table. The actual code using the table had not yet been pushed.

**Comment by twa127** [comment]
@JSa1987 take your point, but because the database updates are cumulative and we will never know what stage of updates a user has applied, then there is a possibility that 200921.sql has been applied, the user has then added data and then later applied 250921.sql and hence looses the data. Could have been simply avoided by modifying the original table format, rather than re-creating it.

The aim when MaxAir ver 1.0 was released was to freeze the database structure, having learnt the lesson with PiHome that it is difficult applying database updates to a live system, but this has proved to be impractical. What I'm trying to establish is the principle that updating the database should not cause any loss of data.
