### ISSUE TITLE
Duplicate zones in Home List

### ISSUE THREAD

**Issue by JSa1987** [pihome-shc/PiHomeHVAC#235]
Hello,

I have noticed that when a zone has more than one relay assigned (for example a circulation pump and radiator valve) the zone is listed multiple times on the dashboard on the home page. See for example "Living Room" in the screenshot below.
![Homelist](https://user-images.githubusercontent.com/62815008/136660627-8a6560b2-28e5-4c13-849b-91d667444a47.png)

This is because the zone will have multiple records in zone_view (one for each relay) and homelist.php pulls all records from this view (see line 153 of homelist.php):
```
$query = "SELECT  * FROM zone_view WHERE `category` = 0  OR `category` = 3 order by index_id asc;";
```
Now using a SELCT DISTINCT instead could prevent this:
```
$query = "SELECT  DISTINCT `id`, `name`, `type`, `category` FROM zone_view WHERE `category` = 0  OR `category` = 3 order by index_id asc;";
```
However, this would then affect the error message on line 303:
```
<p>Controller ID '.$zone_relay_id.' last seen at '.$controler_seen.' </p>
```

Any thoughts on how we could solve this?
Maybe change the error message simply to `<p>Zone Controller last seen at '.$controler_seen.' </p>`?

**Comment by twa127** [comment]
perhaps a better solution to the first issue is

$query = "SELECT `zone`.`id`, `zone`.`name`, `zone_type`.`type`, `zone_type`.`category` FROM `zone`, `zone_type` WHERE (`zone`.`type_id` = `zone_type`.`id`) AND (`zone_type`.`category` = 0 OR `zone_type`.`category` = 3) ORDER BY `zone`.`index_id` ASC;";

The 2nd issue is a bit more complex, should the zone error if any one controller is in error?

**Comment by JSa1987** [comment]
Yes, I believe that is correct... with the current setup we won't know which controller caused the fault flag.

I will try to edit line 153 as you suggested and change line 303 to `<p>Zone Controller last seen at '.$controler_seen.' </p>`and see how it works.

**Comment by twa127** [comment]
@JSa1987 I think your solution for the error condition is probably the way to go, any controller failure on the zone will shut it down, just a bit more difficult to trace the faulty controller

**Comment by JSa1987** [comment]
I have submitted pull request #237 with the fix for this.

**Comment by JSa1987** [comment]
@twa127 I tired the last one and works well. I closed pull request #237 so that you can submit this.

**Comment by twa127** [comment]
Okay will do

**Comment by pihome-shc** [comment]
can we close this issue if no further action required ?

**Comment by twa127** [comment]
I vote yes
