### ISSUE TITLE
Buttons + sensors not working

### ISSUE THREAD

**Issue by JKTechBrno** [pihome-shc/PiHomeHVAC#287]
hello, im trying to click on some buttons like update or install software but nothing happens. And i also tried to add temp sensor, i have DS18B20 but it cant find it..

**Comment by pihome-shc** [comment]
@JKTechBrno can you add more information please, 
can you read DS sensors from shell command? what version you are running?

**Comment by JKTechBrno** [comment]
I just made completly new install, fresh cloned repozitory so i guess its latest version, run setup.php all finished without error. 
Im running on MariaDB, php 7.4 on Apache.

Then i just logged in and it just not working. Yes i can read sensors from shell. And when i click on install soft, nothing happens, no request, no error in console.

**Comment by twa127** [comment]
You need the LAMP stack installed as a pre-requisite, there is an RPi DropBox image available at https://www.dropbox.com/s/yvudvo3amen7t3k/RPI_MaxAir_1_4_131221_no_hotspot_bullseye.zip?dl=0

**Comment by pihome-shc** [comment]
can we close this issue if no further action required ?

**Comment by twa127** [comment]
I vote yes
