### ISSUE TITLE
Change to MQTT password encryption is causing error in gateway.py

### ISSUE THREAD

**Issue by scottagecheeseandcrackers** [pihome-shc/PiHomeHVAC#290]
(Code Version  1.4   - Code Build  221221  - DataBase Version 1.0  - DataBase Build 261121 )

After installing pull request #286 - gateway.py returns the following:

root@maxair:/var/www/cron# python3 gateway.py

                                   
   |  /  |                    /\     ()
   | \  / |    _        /  \         
   | |/| |  / ` | \ / /   / /\ \   | | | '__|
   | |  | | | (| |  >  <   / __ \  | | | |
   ||  ||  _,| //_\ //    _\ || ||

        S M A R T   T H E R M O S T A T

**
* MySensors Wifi/Ethernet/Serial Gateway Communication *
* Script to communicate with MySensors Nodes, for more *
* info please check MySensors API.                     *
*      Build Date: 18/09/2017                          *
*      Version 0.11 - Last Modified 18/08/2021         *
*                                 Have Fun - PiHome.eu *
**

Gateway Type:  Wifi/Ethernet
IP Address:     192.168.68.125
UDP Port:       5003
Setting up MQTT
list index out of range
More info in log file: /var/www/logs/main.log

I note that when I check my mqtt connections in the gui the passwords were not encrypted, despite the update applied.

I disabled the mqtt connections in the gui - at which point i note that the passwords are now showing as encrypted. With all mqtt connections disabled - gateway.py was able to run again without issue.

I have since tried enabling my former mqtt connection - but this again causes issues with gateway.py. I suspect I may have to set up new password hashes and update the database for each connection to fix this issue - possibly - but i'm not sure. Guidanc much appreciated.

**Comment by pihome-shc** [comment]
does that mean user need to disable and enable MQTT? it could be that update applied but exiting system still having clear text password saved.

**Comment by scottagecheeseandcrackers** [comment]
Steps I took to resolve are as follows per advice from @twa127 :

- Disable mqtt connections
- Clear and re-type password for each mqtt connection
- Enable all mqtt connections again.

Once I did this...the system went straight back to normal operation.

Just a thought - would it be possible to add Gateway.py to the job status list - so that you can see if it is running correctly?

**Comment by twa127** [comment]
Fixed in commit #291

**Comment by twa127** [comment]
@scottagecheeseandcrackers the reason that gateway.py is not in the Jobs list is that it is not a scheduled task but runs continually. To check the current status use the GUI in Settings/Node and Zone Configuration/Gateway

**Comment by pihome-shc** [comment]
can we close this issue if no further action required ?

**Comment by twa127** [comment]
I vote yes
