### ISSUE TITLE
 forum software for community

### ISSUE THREAD

**Issue by pihome-shc** [pihome-shc/PiHomeHVAC#4]
i have moved website from blacknight to godady but unfortunately godady don't support Discourse out of the box, may be there is a way to install manually. 

out of the box available options
![image](https://user-images.githubusercontent.com/33334232/97639678-f1125a00-1a36-11eb-914d-47f12d7a9ae3.png)

**Comment by sandreialexandru** [comment]
There is no need to host a forum.
1. Install the Discord app
![Screenshot_20201030_050921](https://user-images.githubusercontent.com/45868553/97655660-4c137380-1a6e-11eb-9071-55e8e3c48558.jpg)
2. Create account
3. Use the invite code that I provided to join an existing server.
