### ISSUE TITLE
General Issues

### ISSUE THREAD

**Issue by pihome-shc** [pihome-shc/PiHomeHVAC#43]
This thread to discuss general issues,

**Comment by pihome-shc** [comment]
relay.php ->Relay ID Node ID for the Relay
it is showing table id rather then actual id

![image](https://user-images.githubusercontent.com/33334232/107836345-b4276480-6d94-11eb-981e-b4c4e7ddf070.png)

**Comment by twa127** [comment]
Just thought that was a bit more informative, the form stores the correct data in the table

**Comment by pihome-shc** [comment]
But if user have multiple controller then there is no way of telling which one is which, i think having node id is better

**Comment by twa127** [comment]
I don't see multiple controllers being an issue, the reason for displaying the id is that this is the value stored in the controller_relays table, not the node_id

**Comment by pihome-shc** [comment]
i think its better to show node_id rather table id. as end user dont have visibility to table structure

**Comment by twa127** [comment]
okay it has some knock on effects, I'll work on it

**Comment by twa127** [comment]
I think this issue is now resolved
