### ISSUE TITLE
Frost Protection

### ISSUE THREAD

**Issue by twa127** [pihome-shc/PiHomeHVAC#44]
The way that frost protection operates needs to be changed for version 2. The reason is that typical configurations will only have 2 zones eg Central Heating and Hot Water but may have temperature sensors located in other parts of the property. In such cases the user may want to provide frost protection based on a temperature sensor not allocated to either the Central Heating or Hot Water zone. Adding extra 'zombie' zones purely to provide a temperature measuring point or to provide a frost protection zone is against the principle of operation of version 2.

In order to provide a flexible and comprehensive solution for frost protection, my proposal is as follows -

When setting up a Temperature Sensor it will be possible to select a frost protection temperature or 0 to disable protection for that particular sensor. If a non zero frost protection temperature is set, then the option is provided to select which zone will be actioned if the temperature falls below the frost protection threshold.

![frost1](https://user-images.githubusercontent.com/46624596/107933234-610d0780-6f76-11eb-8940-dbd276bc64c9.PNG)

The Frost setting menu option will be moved from the Configuration settings menu to the Status  settings menu, it will no longer display a temperature reading, but its status colour will be red is any temperature sensor being used for frost protection is below  its threshold value.

![frost3](https://user-images.githubusercontent.com/46624596/107933648-eb556b80-6f76-11eb-87ee-67d5aae8a563.PNG)

Clicking on the Frost button will display the status of all temperature sensors being used for frost protection

![frost2](https://user-images.githubusercontent.com/46624596/107933779-1b047380-6f77-11eb-8dba-733339e07a01.PNG)

All comments gratefully welcomed

**Comment by sandreialexandru** [comment]
Frost controller is a clever idea for situations like yours. Would it be possible to not activate any controller?

**Comment by twa127** [comment]
Hi,

From the GUI point of view it is not a problem, but the main processing loop in controller.php (boiler.php) works on zones with a status=1, so without some major ish work it could prove difficult

**Comment by sandreialexandru** [comment]
So is it mandatory to have a zone controller?

**Comment by twa127** [comment]
If the frost temperature is set to 0 then frost protection is not active for that sensor and no controller is attached. If frost temperature is any non zero value then you have to attach a controller. This is basically the same as the existing version 1 frost protection, except that each zone can have its independent frost temperature.

What you can't have is a sensor enabled for frost protection without an attached zone. This scenario would involve the system running in bypass mode.

**Comment by sandreialexandru** [comment]
Can a controller be a wired/wireless zone controller or a RPi?

**Comment by twa127** [comment]
Yes no change from previous version, they are added/edited from the Relays menu, which works in a similar manner as the Sensors menu

**Comment by pihome-shc** [comment]
@twa127 very good work, what blue and red dot mean on frost protection status tile and in model?

**Comment by twa127** [comment]
blue = frost protection not active
red = frost protection active, in the model shows if a particular sensor is frost protecting

**Comment by pihome-shc** [comment]
Red when calling for heat. and blue or orange for normal (not calling for heat)

**Comment by twa127** [comment]
okay, I'll leave as red and blue
