### ISSUE TITLE
System Controller Max Running Time

### ISSUE THREAD

**Issue by twa127** [pihome-shc/PiHomeHVAC#47]
At the moment the Max Running Time variable is not being used. I think we need to define how it will operate or drop the feature.

Any thoughts ?

**Comment by sandreialexandru** [comment]
Max Running Time should be used to protect boiler. 
Example: Boiler is running untill max running time condition is met, then boiler stops. After hysteresis time passes, boiler can run again.

**Comment by twa127** [comment]
I monitor the flow and return temps on my boiler as shown below, if a cold day and zone temp is never reached , then boiler would not switch off until the schedule completes as indicated by the flow temperature. By implementing some max running time the zone temperature control of the system would be overridden. As a follow on - how would we choose the value for max running time ?

![boiler](https://user-images.githubusercontent.com/46624596/108049981-e9f07580-7040-11eb-9b79-903ac93dfc4d.png)

**Comment by sandreialexandru** [comment]
Considering that every system is different, I would say that max running time should be user input.

**Comment by sandreialexandru** [comment]
_By implementing some max running time the zone temperature control of the system would be overridden_
The override would only be active until hysteresis passes.

**Comment by twa127** [comment]
hi,

Struggling to see what level of protection this give, say max run time is 60 mins, and hysteresis is 3 min, then you get a 3 min blip every 60 mins, also what would happen to any active zone controllers, would overrun kick in or not ?

**Comment by sandreialexandru** [comment]
You have a point! My boiler already has a "restart after certain time" option. I too agree that max running time would be redundant.

**Comment by twa127** [comment]
:-) I've been running PiHome for some time now and not yet found a need for this feature, but perhaps there are some configurations where it might be needed.

**Comment by twa127** [comment]
Implemented for non HVAC systems. To disable set max run time to 0, otherwise will run for period set and then switch off for hysteresis time before switching back on. Zone override periods will apply for zone relays.

Please give it a try and let me know what you think
