### ISSUE TITLE
Night Climate Mode

### ISSUE THREAD

**Issue by twa127** [pihome-shc/PiHomeHVAC#48]
At the moment a Min and Max temperature are set in the Night Climate GUI, but the system only ever uses the Min value to set a target temperature value. We need to decide if we want to keep using a single target value or to work within a temperature band.

Any thoughts

**Comment by sandreialexandru** [comment]
I'd go with only one target temperature, considering that, even in this case, the temperature still varies 1°-2°

**Comment by twa127** [comment]
Maybe Min and Max are a bit more sensible for a HVAC system

**Comment by pihome-shc** [comment]
i agree, we need min and max other wise night client and full night schedule aren't any different

**Comment by twa127** [comment]
Hi,

I'm confused again :-)

I can see that a single temp night climate schedule would be no different to a 'normal' schedule, but I'm struggling to see how a temperature band would work -

If the zone temperature is above the night climate target and falling then the system will turn on at target + deadband and control around the target temp. 

If below the night climate target then the system will turn on until the  target - deadband is reached.

**Comment by pihome-shc** [comment]
i think you are overthinking this, calling for heat start at min and stop at max off course deadband and weater factor apply as well.

**Comment by twa127** [comment]
I've implemented the last last option above where $temp_cut_out = nc_max_c, which should control between min and max night climate temperatures
