### ISSUE TITLE
Code Update

### ISSUE THREAD

**Issue by twa127** [pihome-shc/PiHomeHVAC#74]
Hi 

I have an experimental python script to check the installed copy of the repository against the github copy and allow any un-matched files to be updated. Please give it a try BUT BEWARE IT WILL OVERWRITE FILES IN /var/www

[update_code.zip](https://github.com/pihome-shc/PiHomeHVAC/files/6052113/update_code.zip)

**Comment by pihome-shc** [comment]
I was thinking the possibility of triggering python script from gui to update maxair

**Comment by twa127** [comment]
I'll see what i can do, maybe a combined GUI to allow both code and database updates

**Comment by pihome-shc** [comment]
There was open source php library for web console, it was single file base pho script to open ssh console on web, may be that can be helpful
